### ISSUE TITLE
Example doesn't work due to output being a string

### ISSUE THREAD

**Issue by DaveSanders** [jspies/raphael.serialize#1]
In your example, it doesn't quite deserialize the json object because you are stringifying the output from the .serialize.json() function.

Your load_json function could include this line to make the example work again:

if (typeof(json) == "string") {json = JSON.parse(json);}

this way the json string gets turned back into an object array which can be processed.

Thanks
Dave

**Comment by jspies** [comment]
Good call. In the apps where I use this, I actually call like this: load_json(JSON.parse(my_json)).

But it makes sense to move it into the load_json function since I am serializing here.

Thanks, I'll update it soon.

**Comment by DaveSanders** [comment]
Yeah, I figured as much.  It only really came to me because the example on the readme.md doesn't work out of the box.  So, I'd either add it to the code, or change the example so that it shows the JSON.parse bit.

Thanks!

**Comment by jspies** [comment]
I updated this today.
