### ISSUE TITLE
No issues, just saying thanks

### ISSUE THREAD

**Issue by smitty1eGH** [jspies/raphael.serialize#10]
There is no joy like having a little problem and locating a solution.
May fortune favor you, sir.

**Comment by jspies** [comment]
This is the best Issue I've ever received. Thanks. If you are on Raphael 2, ElbertF has a version that he forked a long time ago: https://github.com/ElbertF/Raphael.JSON

I haven't used Raphael in a long time, it was just for a client at the time, but Elbert seems to keep it up there.
