### ISSUE TITLE
Text Node "y" position is off

### ISSUE THREAD

**Issue by zgood** [jspies/raphael.serialize#2]
I was using your script the other day (great raphael plugin btw) and it was working fine, but it kept returning the wrong "y" position for my text elements.  It seems this plugin is returning the center "y" of the element when raphael is using the bottom position of the element.

Here is a demo a made up that demonstrates this.  Your plugin returns "50" for the "y" coordinate, but it should be "57.5".

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Test</title>
    <script src="Assetts/js/jquery-1.4.2.min.js" type="text/javascript"></script>
    <script src="Assetts/js/raphael-min.js" type="text/javascript"></script>
    <script src="Assetts/js/raphael.serialize.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            var paper = Raphael('paper', 300, 150);
            var t = paper.text(100, 50, "Raphael");
            t.attr({
                'font-size': 22,
                fill: 'blue'
            });

```
        var json = paper.serialize.json();
        $('#output').html(json);
    });

    function getY(){
        var textNodes = $("#paper > svg > text");
        $.each(textNodes, function(i){
             alert(this.getAttributeNS(null,'y'));
         });
    }
</script>
```

</head>
<body>
    <form id="form1" runat="server">
    <div>
        <div id="paper" style="width:300px; height:150px;"></div>
        <input id="btnGetY" type="button" value="Get Y" onclick="getY()" />
        <br /><br />
        <span id="output"></span>
    </div>
    </form>
</body>
</html>

**Comment by jspies** [comment]
Thanks zgood,

I'm a little confused because you passed 50 into .text() as the y coordinate. Since the text hasn't been moved, wouldn't you expect to get 50 back?

If you saved the paper, then cleared it and restored it, you would have to pass 50 back in to put the text in the same position, 57.5 would move the text down, and pass back 65 when you call getAttributeNS.

The plugin is designed to be able to export a paper and then recreate it in another paper.

**Comment by zgood** [comment]
Yes, I see you are right.  It was my fault for using in a way which it was not intended.  Ultimately I was trying to export an svg file from Raphael not clone the paper, which is the purpose of the plugin.  

I was using it to collected all the nodes and attributes then rebuild it as a svg file and save it on the backend.  It all worked nicely except for my "y" positioning was always off.

I ended up writing my own function to collect Raphael data and create a svg file which works nice in non-IE browsers.  Parsing VML, from what I understand, is a bit more complex.

**Comment by jspies** [comment]
Cool, glad you got it working. It's odd that it comes out differently, but I bet the paper object spits everything out with an offset and is only accurate relatively.
