### ISSUE TITLE
Namespacing does not work in Raphaeljs 2.0

### ISSUE THREAD

**Issue by dmagoo** [jspies/raphael.serialize#5]
I tried this extension vs. Raphael 2.0.  It breaks. In versions of Raphel < 2.0, the namespaced functions run under the context of a paper object. This does not appear to be the case with 2.0.

Documentation on the website says namespaced extensions are supported, but there is an issue posted on github suggesting otherwise:

https://github.com/DmitryBaranovskiy/raphael/pull/430

Perhaps two functions, serialize and unserialize should be sufficient unless there is an intent to support other serializations besides json.

**Comment by jspies** [comment]
I had originally envisioned multiple formats like

serialize.json()
serialize.xml()
serialize.yml()

Which is why I went the namespaced route. I really hope that they fix it. Otherwise it should be easy to just make  as_json() ad from_json() methods. Do they mention a timeline for getting that pull request in?

**Comment by dmagoo** [comment]
That pull is simply a comment change explaining the removal of the namespace functionality. There is this conflicting issue simply stating that functionality is broken, which I hope is the case.

https://github.com/DmitryBaranovskiy/raphael/issues/409

I sent a message to Dmitry B. asking for clarification.

**Comment by dmagoo** [comment]
Just got a message from Dmitry. This change was intentional. I got no elaboration.

**Comment by jspies** [comment]
Thanks. ElbertF submitted a simple fix just moving the paper assignment up in the methods. Should be working now.
