### ISSUE TITLE
empty array after paper.serialize()

### ISSUE THREAD

**Issue by gerpaick** [jspies/raphael.serialize#6]
Hi,
i dont know if it is issue, and maybe it is my mistake. 
i have a paper and i do some drawings. then i have a button, that i click and i fire an event and i need to set a variable with result of paper.serialize(), but i console to see the result i get empty array.

this is my <head> section 
     <script type="text/javascript" src="javascripts/jquery-1.6.4.js"></script> 
     <script type="text/javascript" src="javascripts/raphael.js"></script> 
     <script type="text/javascript" src="javascripts/raphael.serialize.js"></script> 

and in window.onload = function () {...} i have:
...
$('#btnEmail').click(function() {
    $("input#jsonsvg").val(paper.serialize.json());
    alert($("input#jsonsvg").val());
});
...
some drawings...
...
i have tried with console.log, but i get empty array.

can you help me to pint my mistake/error out?

**Comment by AliasIO** [comment]
I'm having the same issue.

``` javascript
Raphael.fn.serialize = {
  json: function() {
    var paper = this;
```

Here `this` references the `json` function, not the `paper` object. I made it work with a (very) ugly hack:

``` javascript
Raphael.fn.serialize = {
  json: function(paper) {
    //var paper = this;
```

You'll need to pass the paper object as an argument:

`var json = paper.serialize.json(paper);`

**Comment by AliasIO** [comment]
Here's a better fix: https://github.com/jspies/raphael.serialize/pull/7/files

**Comment by jspies** [comment]
Yeah, the latest Rafael's don't work with the namespacing I did. I'll see if I can get a fix or a pull in there to correct it.

**Comment by jspies** [comment]
There's a new commit with Elbert's fix up.
