### ISSUE TITLE
Transform matrix values not returned

### ISSUE THREAD

**Issue by danbramall** [jspies/raphael.serialize#8]
Hi,

There seems to be an issue here whereby transform values aren't serialized correctly.  E.g. when viewing source the DOM is like this:

```
<svg height="100%" version="1.1" width="100%" xmlns="http://www.w3.org/2000/svg" style="overflow: hidden; position: relative;"><desc>Created with Raphaël 2.0.1</desc><defs/><path style="" fill="none" stroke="#d9e026" d="M153,74L384,74L384,304L0,304L0,150L153,150L153,74"/><path style="" fill="#333333" stroke="#d9e026" d="M160,160L160,220L220,220A60,60,0,0,0,160,160" transform="matrix(1, 0, 0, 1, 80, 84)"/></svg>
```

However, when that is serialized, it ends up as:

[{"type":"path","fill":"none","path":"M153,74L384,74L384,304L0,304L0,150L153,150L153,74","stroke":"#d9e026","transform":""},{"type":"path","fill":"#333","path":"M160,160L160,220L220,220A60,60,0,0,0,160,160","stroke":"#d9e026","transform":""}]

So the transform matrix doesn't seem to be getting through.

**Comment by jspies** [comment]
Thanks Dan,

There's admittedly some compatibility problems with Raphael 2. The paper object is actually much cleaner and easier to work with and there's a great project that split off of this one here: https://github.com/ElbertF/Raphael.JSON

It's made for Raphael 2

**Comment by danbramall** [comment]
Awesome!  Thanks jspies - really appreciate the quick response.  ElbertF's project seems to do the trick regarding transforms, so all sorted.  Thanks again.
